export const LOAD_DWARVES_SUCCESS = 'LOAD_DWARVES_SUCCESS';
export const SEARCH_DWARVES_BY_NAME = 'SEARCH_DWARVES_BY_NAME';
export const COPY_DWARVES = 'COPY_DWARVES';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
